---
- name: Project Flow Fusion - Application Deployment
  hosts: localhost
  gather_facts: false
  collections:
    - redhat.openshift

  vars:
    project_code_name: flow-fusion
    project_state: absent
    api_url: "https://api.demo.ocp.tm.gmias:6443"
    
  tasks:
    - name: Create a project
      k8s:
        api_version: project.openshift.io/v1
        kind: Project
        name: "{{ project_code_name }}"
        state: "{{ project_state }}"
        host: "{{ api_url }}"
        api_key: "{{ token }}"
        validate_certs: no
