---
- name: Project Flow Fusion - Application Deployment
  hosts: localhost
  gather_facts: false
  collections:
    - redhat.openshift

  vars:
    project_code_name: flow-fusion
    project_state: present
    api_url: "https://api.demo.ocp.tm.gmias:6443"
    db_name: flow_fusion
    db_user: flow_fusion_user
    db_password: redhat
    
  tasks:
    - name: Create a namespace for the project
      k8s:
        api_version: v1
        kind: Namespace
        name: "{{ project_code_name }}"
        state: "{{ project_state }}"
        host: "{{ api_url }}"
        api_key: "{{ token }}"
        validate_certs: no

    - name: Deployment erstellen
      k8s:
        state: "{{ project_state }}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ project_code_name }}-app"
            namespace: "{{ project_code_name }}"
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: "{{ project_code_name }}-app"
            template:
              metadata:
                labels:
                  app: "{{ project_code_name }}-app"
              spec:
                containers:
                  - name: "{{ project_code_name }}-app"
                    image: arwthomasm/todo-app:latest
                    ports:
                      - containerPort: 8080
                    env:
                      - name: MYSQL_HOST
                        value: "172.27.55.221"
                      - name: MYSQL_USER
                        value: "{{ db_user }}"
                      - name: MYSQL_PASSWORD
                        value: "{{ db_password }}"
                      - name: MYSQL_DB
                        value: "{{ db_name }}"
        host: "{{ api_url }}"
        api_key: "{{ token }}"
        validate_certs: no
